/**
 * WegUp Adaptive AI Practice & Quiz Generator
 * Generates custom, on-demand placement assessment questions across any technical topic.
 */

import { generateGeminiJSON, isLiveAIMode } from "./api.js";
import { uid, getState, saveState, logActivity } from "./state.js";

export const POPULAR_TOPICS = [
  "Data Structures & Algorithms",
  "SQL & Database Querying",
  "JavaScript & Web Architecture",
  "Operating Systems & Multithreading",
  "System Design & Microservices",
  "Computer Networks & HTTP Protocols",
  "React & Modern Frontend",
  "Python & OOP Principles"
];

const LOCAL_QUESTION_BANK = {
  "Data Structures & Algorithms": [
    {
      text: "What is the worst-case time complexity of finding an element in an unsorted array of size N versus a balanced binary search tree (BST)?",
      options: ["O(N) and O(log N)", "O(1) and O(N)", "O(log N) and O(N)", "O(N) and O(1)"],
      answer: 0,
      explanation: "Unsorted array lookup requires scanning every element in the worst case (O(N)), while a balanced BST divides search space in half at each step (O(log N))."
    },
    {
      text: "Which data structure is fundamentally used to implement Breadth-First Search (BFS) on a graph?",
      options: ["Stack", "Queue", "Heap / Priority Queue", "Hash Map"],
      answer: 1,
      explanation: "BFS explores nodes level by level in First-In-First-Out (FIFO) order, which is natively provided by a Queue data structure."
    },
    {
      text: "What is the space complexity of quicksort in the average case?",
      options: ["O(1)", "O(log N)", "O(N)", "O(N log N)"],
      answer: 1,
      explanation: "Even though quicksort is in-place, the recursive call stack uses O(log N) auxiliary space in the average case."
    }
  ],
  "SQL & Database Querying": [
    {
      text: "What is the primary operational difference between the WHERE clause and the HAVING clause in SQL?",
      options: [
        "WHERE works only on numbers; HAVING works on text",
        "WHERE filters individual rows before grouping; HAVING filters aggregated groups after GROUP BY",
        "HAVING is executed before WHERE in the query pipeline",
        "There is no difference; they are aliases"
      ],
      answer: 1,
      explanation: "WHERE filters rows before any aggregate functions are calculated; HAVING filters the groups generated by GROUP BY based on aggregate criteria."
    },
    {
      text: "Which SQL index type is most effective for range queries (e.g. WHERE salary BETWEEN 30000 AND 60000)?",
      options: ["Hash Index", "B-Tree Index", "Bitmap Index", "Full-text Index"],
      answer: 1,
      explanation: "B-Tree indexes maintain sorted order of keys, making range searches and ordered traversal very efficient (O(log N)). Hash indexes only support equality."
    },
    {
      text: "What does an INNER JOIN return when there are no matching rows between two tables?",
      options: ["All rows from the left table with NULLs", "An empty result set", "All rows from both tables", "A syntax error"],
      answer: 1,
      explanation: "INNER JOIN strictly returns records that satisfy the matching join condition on both sides. If none match, zero rows are returned."
    }
  ],
  "General": [
    {
      text: "What does the idempotent property mean in the context of RESTful HTTP methods?",
      options: [
        "The request takes zero milliseconds to execute",
        "Making identical requests multiple times produces the same server state as a single request",
        "The endpoint requires no authentication",
        "The request cannot return an HTTP 500 error"
      ],
      answer: 1,
      explanation: "An HTTP method is idempotent if the intended effect on the server of multiple identical requests is the same as for a single request (e.g., GET, PUT, DELETE)."
    },
    {
      text: "In distributed systems, what does the CAP theorem state is impossible to guarantee simultaneously in the presence of network partitions?",
      options: [
        "Cost, Accuracy, and Performance",
        "Consistency and Availability",
        "Concurrency and Atomicity",
        "Caching and Pagination"
      ],
      answer: 1,
      explanation: "The CAP theorem proves that in any asynchronous network subject to partitions (P), a distributed data store can guarantee either Consistency (C) or Availability (A), but not both."
    }
  ]
};

export async function generateQuiz(topic, difficulty = "Intermediate", count = 4) {
  if (isLiveAIMode()) {
    try {
      const prompt = `
Generate a high-quality, placement-focused technical quiz for an engineering student.

TOPIC: ${topic}
DIFFICULTY: ${difficulty}
QUESTION COUNT: ${count}

REQUIREMENTS:
1. Each question must test real understanding, problem-solving, or industry best practices (avoid trivial syntax trivia).
2. Exactly 4 realistic options per question.
3. Accurate 0-indexed correct answer.
4. Clear, educational explanation detailing why the correct answer is right.

Return JSON in this EXACT structure:
{
  "topic": "${topic}",
  "questions": [
    {
      "text": "Question statement here?",
      "options": ["Option A", "Option B", "Option C", "Option D"],
      "answer": 1,
      "explanation": "Explanation here..."
    }
  ]
}
`;
      const result = await generateGeminiJSON(prompt, "You are a technical exam author for software engineering campus placements.");
      if (result && Array.isArray(result.questions) && result.questions.length > 0) {
        return result.questions;
      }
    } catch (err) {
      console.warn("Live Gemini quiz generation failed, falling back to local questions:", err);
    }
  }

  // Local fallback
  const pool = LOCAL_QUESTION_BANK[topic] || LOCAL_QUESTION_BANK["General"];
  return pool.slice(0, count);
}

export function recordQuizResult(topic, correctCount, totalCount) {
  const state = getState();
  if (!state.quizAttempts) state.quizAttempts = [];
  const percent = Math.round((correctCount / Math.max(1, totalCount)) * 100);

  state.quizAttempts.unshift({
    id: uid(),
    date: new Date().toISOString(),
    topic,
    correct: correctCount,
    total: totalCount,
    percentage: percent
  });

  logActivity(`Completed quiz on ${topic} (${correctCount}/${totalCount} - ${percent}%)`, "quiz");
  saveState();
}
